- hosts: php_hosts
  vars:
    php_version: '7.3'
    php_versions_install_recommends: True
  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - geerlingguy.php-versions
    - geerlingguy.php
